language: csharp
solution: ext_pp.sln
dotnet: 2.1.502
mono: none

matrix:
  include:
    - dotnet: 2.1.502
      mono: none
      env:
        - SOLUTION="ext_pp.sln"
        - BUILDCONFIG="Release"

install:
  - dotnet restore 

script:
  - dotnet build $SOLUTION -c $BUILDCONFIG

after_script:
  - dotnet test $SOLUTION
  - bash <(curl -s https://codecov.io/bash)