language: csharp
solution: ext_compiler.sln
dotnet: 2.1.502
mono: none

envs:
  - SOLUTION=ext_compiler.sln
  - BUILD_CONFIG=Release

install:
  - dotnet restore 

script:
  - dotnet build $SOLUTION -c $BUILD_CONFIG

after_script:
  - dotnet test $SOLUTION