language: csharp
solution: ext_compiler.sln
dotnet: 2.1.502
mono: none



before_install:
  - sudo apt-get install nunit-console

install:
  - dotnet restore ext_compiler.sln

script:
  - dotnet build ext_compiler.sln -c Release

after_script:
  - dotnet test ext_compiler.sln