language: csharp
solution: ext_compiler.sln
dotnet: 2.1.502
mono: none

envs:
  - SOLUTION="ext_compiler.sln"
  - BUILDCONFIG="Release"

install:
  - dotnet restore 

script:
  - dotnet build $SOLUTION -c $BUILDCONFIG

after_script:
  - dotnet test $SOLUTION